all: .phony

.phony:
	cd AmbientOcclusion & make
	cd BunnyBenchmark & make
	cd HelloCollider & make
	cd HelloMesh & make
	cd HelloRealtimeRadiosity & make
	cd HelloVision & make
	cd Lightmaps & make
	cd Water & make

clean:
	cd AmbientOcclusion & make clean
	cd BunnyBenchmark & make clean
	cd HelloCollider & make clean
	cd HelloMesh & make clean
	cd HelloRealtimeRadiosity & make clean
	cd HelloVision & make clean
	cd Lightmaps & make clean
	cd Water & make clean
