all: .phony

.phony:
	cd BunnyBenchmark & make
	cd HelloCollider & make
	cd HelloMesh & make
	cd HelloRealtimeRadiosity & make
	cd HelloVision & make

clean:
	cd BunnyBenchmark & make clean
	cd HelloCollider & make clean
	cd HelloMesh & make clean
	cd HelloRealtimeRadiosity & make clean
	cd HelloVision & make clean
