all: .phony

.phony:
	cd RRMesh & make
	cd RRCollider & make
	cd RRVision & make
	cd DemoEngine & make
	cd LightsprintGL & make
	cd FCSS & make
	cd World & make
	cd RR & make

clean:
	cd RRMesh & make clean
	cd RRCollider & make clean
	cd RRVision & make clean
	cd DemoEngine & make clean
	cd LightsprintGL & make clean
	cd FCSS & make clean
	cd World & make clean
	cd RR & make clean
