all: .phony

.phony:
	cd RRIllumination & make
	cd RRMesh & make
	cd RRCollider & make
	cd RRVision & make
	cd DemoEngine & make
	cd RRGPUOpenGL & make
	cd FCSS & make
	cd World & make
	cd RR & make

clean:
	cd RRIllumination & make clean
	cd RRMesh & make clean
	cd RRCollider & make clean
	cd RRVision & make clean
	cd DemoEngine & make clean
	cd RRGPUOpenGL & make clean
	cd FCSS & make clean
	cd World & make clean
	cd RR & make clean
