# include platform-specific configuration

CFG_DIR = ../configs
-include $(CFG_DIR)/current

ifdef CONFIG
include $(CFG_DIR)/$(CONFIG)
endif

# general project settings

PROJECT = LightsprintIO

ifdef STATIC
CFG_TYPE = lib
TARGET = ../../lib/$(CONFIG)/lib$(PROJECT).a
else
CFG_TYPE = dll
TARGET = ../../bin/$(CONFIG)/lib$(PROJECT).so
endif

OBJ_DIR = ../../tmp/$(PROJECT)/$(CONFIG)

# project-dependent compiler/preprocessor flags

ifdef STATIC
CPP_FLAGS += -DRR_IO_STATIC
endif
CPP_FLAGS += -DLINUX

# source files

SOURCES = \
Import3DS/Model_3DS.cpp \
Import3DS/RRObject3DS.cpp \
ImportAssimp/RRObjectAssimp.cpp \
ImportAssimp/code/MDLMaterialLoader.cpp \
ImportAssimp/code/B3DImporter.cpp \
ImportAssimp/code/ObjFileMtlImporter.cpp \
ImportAssimp/code/BaseImporter.cpp \
ImportAssimp/code/TerragenLoader.cpp \
ImportAssimp/code/Assimp.cpp \
ImportAssimp/code/ConvertToLHProcess.cpp \
ImportAssimp/code/SpatialSort.cpp \
ImportAssimp/code/SceneCombiner.cpp \
ImportAssimp/code/SMDLoader.cpp \
ImportAssimp/code/IRRLoader.cpp \
ImportAssimp/code/CalcTangentsProcess.cpp \
ImportAssimp/code/DefaultIOSystem.cpp \
ImportAssimp/code/XFileImporter.cpp \
ImportAssimp/code/PlyLoader.cpp \
ImportAssimp/code/IRRShared.cpp \
ImportAssimp/code/ASEParser.cpp \
ImportAssimp/code/ColladaLoader.cpp \
ImportAssimp/code/RemoveComments.cpp \
ImportAssimp/code/DefaultIOStream.cpp \
ImportAssimp/code/VertexTriangleAdjacency.cpp \
ImportAssimp/code/IRRMeshLoader.cpp \
ImportAssimp/code/LWOLoader.cpp \
ImportAssimp/code/NFFLoader.cpp \
ImportAssimp/code/ObjFileImporter.cpp \
ImportAssimp/code/DefaultLogger.cpp \
ImportAssimp/code/FindInvalidDataProcess.cpp \
ImportAssimp/code/3DSLoader.cpp \
ImportAssimp/code/SortByPTypeProcess.cpp \
ImportAssimp/code/GenFaceNormalsProcess.cpp \
ImportAssimp/code/MD3Loader.cpp \
ImportAssimp/code/LimitBoneWeightsProcess.cpp \
ImportAssimp/code/LWOAnimation.cpp \
ImportAssimp/code/BaseProcess.cpp \
ImportAssimp/code/MDLLoader.cpp \
ImportAssimp/code/UnrealLoader.cpp \
ImportAssimp/code/LWOBLoader.cpp \
ImportAssimp/code/ColladaParser.cpp \
ImportAssimp/code/ImproveCacheLocality.cpp \
ImportAssimp/code/aiAssert.cpp \
ImportAssimp/code/MD2Loader.cpp \
ImportAssimp/code/RawLoader.cpp \
ImportAssimp/code/ACLoader.cpp \
ImportAssimp/code/FixNormalsStep.cpp \
ImportAssimp/code/OptimizeGraph.cpp \
ImportAssimp/code/PlyParser.cpp \
ImportAssimp/code/OFFLoader.cpp \
ImportAssimp/code/FindInstancesProcess.cpp \
ImportAssimp/code/SplitLargeMeshes.cpp \
ImportAssimp/code/HMPLoader.cpp \
ImportAssimp/code/BVHLoader.cpp \
ImportAssimp/code/GenVertexNormalsProcess.cpp \
ImportAssimp/code/FindDegenerates.cpp \
ImportAssimp/code/STLLoader.cpp \
ImportAssimp/code/PretransformVertices.cpp \
ImportAssimp/code/ASELoader.cpp \
ImportAssimp/code/OptimizeMeshes.cpp \
ImportAssimp/code/MaterialSystem.cpp \
ImportAssimp/code/TriangulateProcess.cpp \
ImportAssimp/code/ComputeUVMappingProcess.cpp \
ImportAssimp/code/CSMLoader.cpp \
ImportAssimp/code/ValidateDataStructure.cpp \
ImportAssimp/code/SkeletonMeshBuilder.cpp \
ImportAssimp/code/LWSLoader.cpp \
ImportAssimp/code/XFileParser.cpp \
ImportAssimp/code/OgreImporter.cpp \
ImportAssimp/code/JoinVerticesProcess.cpp \
ImportAssimp/code/AssimpPCH.cpp \
ImportAssimp/code/Q3DLoader.cpp \
ImportAssimp/code/StandardShapes.cpp \
ImportAssimp/code/3DSConverter.cpp \
ImportAssimp/code/ObjFileParser.cpp \
ImportAssimp/code/DXFLoader.cpp \
ImportAssimp/code/MD5Parser.cpp \
ImportAssimp/code/MD5Loader.cpp \
ImportAssimp/code/TextureTransform.cpp \
ImportAssimp/code/RemoveRedundantMaterials.cpp \
ImportAssimp/code/TargetAnimation.cpp \
ImportAssimp/code/SGSpatialSort.cpp \
ImportAssimp/code/ScenePreprocessor.cpp \
ImportAssimp/code/Importer.cpp \
ImportAssimp/code/LWOMaterial.cpp \
ImportAssimp/code/RemoveVCProcess.cpp \
ImportAssimp/code/MDCLoader.cpp \
ImportAssimp/contrib/irrXML/irrXML.cpp \
ImportAssimp/contrib/zlib/trees.c \
ImportAssimp/contrib/zlib/zutil.c \
ImportAssimp/contrib/zlib/deflate.c \
ImportAssimp/contrib/zlib/inffast.c \
ImportAssimp/contrib/zlib/compress.c \
ImportAssimp/contrib/zlib/crc32.c \
ImportAssimp/contrib/zlib/adler32.c \
ImportAssimp/contrib/zlib/inftrees.c \
ImportAssimp/contrib/zlib/inflate.c \
ImportAssimp/contrib/ConvertUTF/ConvertUTF.c \
ImportFCollada/RRObjectFCollada.cpp \
ImportImages/ImportFreeImage.cpp \
ImportMGF/RRObjectMGF.cpp \
ImportMGF/badarg.c \
ImportMGF/context.c \
ImportMGF/fvect.c \
ImportMGF/lookup.c \
ImportMGF/object.c \
ImportMGF/parser.c \
ImportMGF/words.c \
ImportMGF/xf.c \
ImportOBJ/RRObjectOBJ.cpp \
ImportOpenCollada/RRObjectOpenCollada.cpp \
ImportQuake3/Q3Loader.cpp \
ImportQuake3/RRObjectBSP.cpp \
ImportScene.cpp

# libraries

# include directories

INC_DIRS = .
INC_DIRS += ../../include

# library directories

LIB_DIRS = .

# include the core part of the makefile

include $(CFG_DIR)/../makefile.core
