# include platform-specific configuration

CFG_DIR = ../configs
-include $(CFG_DIR)/current

ifdef CONFIG
include $(CFG_DIR)/$(CONFIG)
endif

# general project settings

PROJECT = LightsprintIO

ifdef STATIC
CFG_TYPE = lib
TARGET = ../../lib/$(CONFIG)/lib$(PROJECT).a
else
CFG_TYPE = dll
TARGET = ../../bin/$(CONFIG)/lib$(PROJECT).so
endif

OBJ_DIR = ../../tmp/$(PROJECT)/$(CONFIG)

# project-dependent compiler/preprocessor flags

CPP_FLAGS += $(CPP_IO_FLAGS)
CPP_FLAGS += -DRR_IO_BUILD
CPP_FLAGS += -DLINUX
CPP_FLAGS += -DGENERATEDSAXPARSER_XMLPARSER_EXPAT -DPCRE_STATIC -DCOMPILED_FROM_DSP

# source files

SOURCES = \
3DS/Model_3DS.cpp \
3DS/RRObject3DS.cpp \
Assimp/RRObjectAssimp.cpp \
FFmpeg/RRBufferFFmpeg.cpp \
FFmpeg/RRBufferFFmpeg.h \
FreeImage/ImportFreeImage.cpp \
Isolation/RRSceneIsolation.cpp \
Lightsprint/RRObjectLightsprint.cpp \
Lightsprint/portable_binary_iarchive.cpp \
Lightsprint/portable_binary_oarchive.cpp \
MGF/RRObjectMGF.cpp \
MGF/badarg.c \
MGF/context.c \
MGF/fvect.c \
MGF/lookup.c \
MGF/object.c \
MGF/parser.c \
MGF/words.c \
MGF/xf.c \
OBJ/RRObjectOBJ.cpp \
OpenCollada/RRObjectOpenCollada.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUHashFunctions.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUIDList.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUNativeString.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUPcreCompiledPattern.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUPrecompiledHeaders.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUStringUtils.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUURI.cpp \
OpenCollada/COLLADABaseUtils/src/COLLADABUUtils.cpp \
OpenCollada/COLLADABaseUtils/src/Math/COLLADABUMathMatrix3.cpp \
OpenCollada/COLLADABaseUtils/src/Math/COLLADABUMathMatrix4.cpp \
OpenCollada/COLLADABaseUtils/src/Math/COLLADABUMathQuaternion.cpp \
OpenCollada/COLLADABaseUtils/src/Math/COLLADABUMathUtils.cpp \
OpenCollada/COLLADABaseUtils/src/Math/COLLADABUMathVector3.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWAxisInfo.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWCamera.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWColor.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWConstants.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWEffect.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWEffectCommon.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWFileInfo.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWFloatOrDoubleArray.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWFormula.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWFormulas.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWGeometry.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWImage.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWInstanceKinematicsScene.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWKinematicsController.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWKinematicsModel.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWKinematicsScene.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWLight.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWLoaderUtils.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWMaterial.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWMatrix.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWMesh.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWMeshPrimitive.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWMorphController.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWNode.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWPrecompiledHeaders.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWRenderState.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWRoot.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWRotate.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWSampler.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWScale.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWSkinController.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWSkinControllerData.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWSpline.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWTexture.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWTransformation.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWTranslate.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWUniqueId.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWValidate.cpp \
OpenCollada/COLLADAFramework/src/COLLADAFWVisualScene.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLAssetLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLCOLLADACsymbol.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLDocumentProcessor.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLExtraDataElementHandler.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLExtraDataLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLFileLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLFilePartLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLFormulasLinker.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLFormulasLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLGeometryLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLGeometryMaterialIdInfo.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLIError.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLIErrorHandler.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLIExtraDataCallbackHandler.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLIFilePartLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLInputUnshared.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLInstanceArticulatedSystemLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLInstanceKinematicsModelLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLIParserImpl14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLIParserImpl15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLJointsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLKinematicsIntermediateData.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLKinematicsSceneCreator.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryAnimationsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryArticulatedSystemsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryCamerasLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryControllersLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryEffectsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryFormulasLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryImagesLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryJointsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryKinematicsModelsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryKinematicsScenesLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryLightsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryMaterialsLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLibraryNodesLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLMeshLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLMeshPrimitiveInputList.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLNodeLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLPostProcessor.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLPrecompiledHeaders.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLRootParser14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLRootParser15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSaxFWLError.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSaxParserError.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSaxParserErrorHandler.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSceneLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSidAddress.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSidTreeNode.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSourceArrayLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLSplineLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLTransformationLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLTypes.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLVersionParser.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/COLLADASaxFWLVisualSceneLoader.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLAssetLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLColladaParserAutoGen14Private.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLColladaParserAutoGen14PrivateEnums.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLColladaParserAutoGen14PrivateFindElementHash.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLColladaParserAutoGen14PrivateFunctionMap.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLColladaParserAutoGen14PrivateFunctionMapFactory.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLColladaParserAutoGen14PrivateNameMap.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLGeometryLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryAnimationsLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryCamerasLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryControllersLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryEffectsLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryImagesLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryLightsLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryMaterialsLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLLibraryNodesLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLMeshLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLNodeLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLSceneLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLSourceArrayLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLSplineLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated14/COLLADASaxFWLVisualSceneLoader14.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLAssetLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLColladaParserAutoGen15Private.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLColladaParserAutoGen15PrivateEnums.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLColladaParserAutoGen15PrivateFindElementHash.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLColladaParserAutoGen15PrivateFunctionMap.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLColladaParserAutoGen15PrivateFunctionMapFactory.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLColladaParserAutoGen15PrivateNameMap.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLFormulasLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLGeometryLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryAnimationsLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryArticulatedSystemsLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryCamerasLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryControllersLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryEffectsLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryFormulasLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryImagesLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryJointsLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryKinematicsModelsLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryKinematicsScenesLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryLightsLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryMaterialsLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLLibraryNodesLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLMeshLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLNodeLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLSceneLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLSourceArrayLoader15.cpp \
OpenCollada/COLLADASaxFrameworkLoader/src/generated15/COLLADASaxFWLVisualSceneLoader15.cpp \
OpenCollada/Externals/expat/lib/xmlparse.c \
OpenCollada/Externals/expat/lib/xmlrole.c \
OpenCollada/Externals/expat/lib/xmltok.c \
OpenCollada/Externals/expat/lib/xmltok_impl.c \
OpenCollada/Externals/expat/lib/xmltok_ns.c \
OpenCollada/Externals/MathMLSolver/src/MathMLEvaluatorVisitor.cpp \
OpenCollada/Externals/MathMLSolver/src/MathMLSerializationUtil.cpp \
OpenCollada/Externals/MathMLSolver/src/MathMLSerializationVisitor.cpp \
OpenCollada/Externals/MathMLSolver/src/MathMLSolverFunctionExtensions.cpp \
OpenCollada/Externals/MathMLSolver/src/MathMLSolverPrecompiled.cpp \
OpenCollada/Externals/MathMLSolver/src/MathMLString.cpp \
OpenCollada/Externals/MathMLSolver/src/MathMLSymbolTable.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTArithmeticExpression.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTBinaryComparisionExpression.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTConstantExpression.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTFragmentExpression.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTFunctionExpression.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTLogicExpression.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTStringVisitor.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTUnaryArithmeticExpression.cpp \
OpenCollada/Externals/MathMLSolver/src/AST/MathMLASTVariableExpression.cpp \
OpenCollada/Externals/pcre/src/pcre_chartables.c \
OpenCollada/Externals/pcre/src/pcre_compile.c \
OpenCollada/Externals/pcre/src/pcre_exec.c \
OpenCollada/Externals/pcre/src/pcre_globals.c \
OpenCollada/Externals/pcre/src/pcre_newline.c \
OpenCollada/Externals/pcre/src/pcre_tables.c \
OpenCollada/Externals/pcre/src/pcre_try_flipped.c \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserCoutErrorHandler.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserExpatSaxParser.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserNamespaceStack.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserParser.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserParserError.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserParserTemplate.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserParserTemplateBase.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserRawUnknownElementHandler.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserSaxParser.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserStackMemoryManager.cpp \
OpenCollada/GeneratedSaxParser/src/GeneratedSaxParserUtils.cpp \
Quake3/Q3Loader.cpp \
Quake3/RRObjectBSP.cpp \
IO.cpp

# libraries

LIBS += $(CORE_LIBS) $(IO_DEPS)

# include directories

INC_DIRS = .
INC_DIRS += ../../include \
OpenCollada/COLLADASaxFrameworkLoader/include/generated15 \
OpenCollada/COLLADASaxFrameworkLoader/include/generated14 \
OpenCollada/COLLADASaxFrameworkLoader/include \
OpenCollada/COLLADABaseUtils/include \
OpenCollada/COLLADAFramework/include \
OpenCollada/GeneratedSaxParser/include \
OpenCollada/Externals/expat/lib \
OpenCollada/Externals/MathMLSolver/include \
OpenCollada/Externals/MathMLSolver/include/AST \
OpenCollada/Externals/pcre/include \
OpenCollada/Externals/UTF/include

# library directories

LIB_DIRS = .

# include the core part of the makefile

include $(CFG_DIR)/../makefile.core
